name: Run diff-cover with reviewdog
description: 🐶 Run diff-cover with reviewdog on pull requests to improve code review experience.
author: itsmycargo

inputs:
  github_token:
    description: 'GITHUB_TOKEN'
    required: true
  diff_cover_version:
    description: 'diff-cover version'
  diff_cover_flags:
    description: 'diff-cover flags.'
    default: ''
  coverage_files:
    description: 'Coverage files to process'
    required: true
    default: '**/coverage.xml'
  tool_name:
    description: 'Tool name to use for reviewdog reporter'
    default: 'diff-cover'
  level:
    description: 'Report level for reviewdog [info,warning,error]'
    default: 'error'
  reporter:
    description: |
      Reporter of reviewdog command [github-pr-check,github-pr-review].
      Default is github-pr-check.
    default: 'github-pr-check'
  filter_mode:
    description: |
      Filtering mode for the reviewdog command [added,diff_context,file,nofilter].
      Default is added.
    default: 'added'
  fail_on_error:
    description: |
      Exit code for reviewdog when errors are found [true,false]
      Default is `false`.
    default: 'false'
  reviewdog_flags:
    description: 'Additional reviewdog flags'
    default: ''
runs:
  using: 'composite'
  steps:
    - run: $GITHUB_ACTION_PATH/script.sh
      shell: sh
      env:
        REVIEWDOG_VERSION: v0.13.0
        # INPUT_<VARIABLE_NAME> is not available in Composite run steps
        # https://github.community/t/input-variable-name-is-not-available-in-composite-run-steps/127611
        INPUT_GITHUB_TOKEN: ${{ inputs.github_token }}
        INPUT_DIFF_COVER_VERSION: ${{ inputs.diff_cover_version }}
        INPUT_DIFF_COVER_FLAGS: ${{ inputs.diff_cover_flags }}
        INPUT_COVERAGE_FILES: ${{ inputs.coverage_files }}
        INPUT_TOOL_NAME: ${{ inputs.tool_name }}
        INPUT_LEVEL: ${{ inputs.level }}
        INPUT_REPORTER: ${{ inputs.reporter }}
        INPUT_FILTER_MODE: ${{ inputs.filter_mode }}
        INPUT_FAIL_ON_ERROR: ${{ inputs.fail_on_error }}
        INPUT_REVIEWDOG_FLAGS: ${{ inputs.reviewdog_flags }}
branding:
  icon: 'check-circle'
  color: 'red'
